- name: Update or fetch for first time the source files for application
  git: repo=https://github.com/jannekai/exmodfi.git dest={{site_base_dir}}/deploy
  register: site_updated
  become_user: "{{site_user}}"

- name: Install and update Hex and Rebar
  shell: mix do local.hex --force, local.rebar --force
  environment:
    MIX_ENV: prod
  become_user: "{{site_user}}"
  when: site_updated.changed

- name: Build the server
  shell: mix do deps.get, deps.compile, compile chdir="{{site_base_dir}}/deploy"
  environment:
    MIX_ENV: prod
  become_user: "{{site_user}}"
  when: site_updated.changed

- name: Render upstart configuration template
  template: src=upstart.conf.j2 dest=/etc/init/{{site_name}}.conf

- name: Render nginx configuration template
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{site_name}}

- name: Restart nginx service
  service: name=nginx state=restarted

- name: Restart exmodfi service
  service: name=exmodfi state=restarted
