- name: Update or fetch for first time the source files for application
  git: repo=https://github.com/jannekai/exmodfi.git dest={{deployment_dir}}
  become_user: "{{server_user}}"

- name: Cleanup previous build artifacts
  shell: make clean|logger chdir={{deployment_dir}}
  become_user: "{{server_user}}"

- name: Update build tools and dependencies
  shell: make deps|logger chdir={{deployment_dir}}
  become_user: "{{server_user}}"

- name: Build the server
  shell: make prod|logger chdir={{deployment_dir}}
  become_user: "{{server_user}}"

- name: Render upstart configuration template
  template: src=upstart.conf.j2 dest=/etc/init/{{server_name}}.conf

- name: Render nginx configuration template
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{server_name}}

- name: Restart nginx service
  service: name=nginx state=restarted

- name: Restart exmodfi service
  service: name=exmodfi state=restarted
